---
units:
- name: NetworkManager.service
  action: enable
- name: sddm.service
  action: enable
- name: systemd-timesyncd.service
  action: enable
- name: systemd-networkd.service
  action: disable
- name: systemd-networkd.socket
  action: disable
- name: iwd.service
  action: disable
- name: choose-mirror.service
  action: disable
- name: pacman-init.service
  action: disable
