---
defaultGroups:
- users
- lp
- video
- network
- storage
- wheel
- audio
autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: true
doReusePassword: true
passwordRequirements:
  minLength: -1
  maxLength: -1
userShell: /bin/bash
